### ISSUE TITLE
Add pattern_suggest for bad patterns in ES

### ISSUE THREAD

**Issue by ayanogami** [NAIST-SD-PBL-PAL/Teddy-plus#29]
if it can not matching, the system returns "mismatch"

**Comment by ayanogami** [comment]
* pattern_suggest property has pythonic pattern's name
* pythonic pattern's example code in another property "good example"

**Comment by Phancisth** [comment]
Included in an accidental merge [#44](https://github.com/NAIST-SD-PBL-PAL/Teddy-plus/pull/44)
